### ISSUE TITLE
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor

### ISSUE THREAD

**Issue by pvtrn** [lithium0003/whisper_for_iOS#1]
error in this line

--> traced_model = torch.jit.trace(model.encoder, input_mel)

ModelDimensions(n_mels=80, n_audio_ctx=1500, n_audio_state=768, n_audio_head=12, n_audio_layer=12, n_vocab=51865, n_text_ctx=448, n_text_state=768, n_text_head=12, n_text_layer=12)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-8-6740c01055ee>](https://n4axni0xnrm-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20221005-060049-RC00_479005510#) in <module>
     48 
     49 size = "small"
---> 50 convert_encoder(size)
     51 convert_decoder(size)

10 frames
[/usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py](https://n4axni0xnrm-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20221005-060049-RC00_479005510#) in _conv_forward(self, input, weight, bias)
    302                             _single(0), self.dilation, self.groups)
    303         return F.conv1d(input, weight, bias, self.stride,
--> 304                         self.padding, self.dilation, self.groups)
    305 
    306     def forward(self, input: Tensor) -> Tensor:

RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor

**Comment by lithium0003** [comment]
Thanks for reporting bug!
