### ISSUE TITLE
Always translates into English

### ISSUE THREAD

**Issue by pvtrn** [lithium0003/whisper_for_iOS#2]
Transcription does not always work. At some point, any language is always automatically translated into English and this cannot be canceled

**Comment by lithium0003** [comment]
Transcription sometimes returns strange behavior, I speak English and use transcription but recognize as Japanese and show Japanese. This model maybe pull into the speaker's mother tongue.
Same sound sample returns different behaviors from original model?

**Comment by pvtrn** [comment]
![image](https://user-images.githubusercontent.com/3105719/194687367-46de186d-968e-4af3-b2ce-f5d2a5f6b71b.jpeg)


I can't understand how to manage this program. It translates into English, and I speak Russian.

**Comment by lithium0003** [comment]
Thanks, I figured out. It drops timestamp tokens implementation causes this situation. I try fix it.
