### ISSUE TITLE
decoder unable to untilize GPU/Neural Engine

### ISSUE THREAD

**Issue by yujinqiu** [lithium0003/whisper_for_iOS#5]
After convert the model, in Xcode  select the model and  in performance tab, we can benchmark model. 
I found that `encoder.mlpackage` can run on GPU/Neural Engine. 
<img width="1455" alt="image" src="https://user-images.githubusercontent.com/785405/213390211-2319946f-f6b7-496d-a31e-276ad9888565.png">
But the `decoder.mlpackage` look like unable to run on GPU/Neural Engine, I pretty sure I set the compute unit to ALL. 
<img width="1499" alt="image" src="https://user-images.githubusercontent.com/785405/213390816-38c608e9-cb36-420c-bc74-7e49f651f655.png">

This is quite import for performance,  maybe you have some idea of why. 
Looking forward to your reply.

**Comment by lithium0003** [comment]
Thanks for information.
It happens because decoder input shape is set with [1:448] range shape. I'm testing with shape fixed 448 size, it maybe work well NeuralEngine/GPU.
